version: "3"

services:
    app:
        image: drakona/php:8-symfony
        depends_on:
            - db
        volumes:
            - .:/srv

    nginx:
        image: drakona/nginx:7.4-vanilla
        depends_on:
            - app
        volumes:
            - .:/srv
        ports:
            - "8000:80"